# Generated by Django 5.0 on 2024-01-05 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=15)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=15)),
                ('solde', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=100)),
                ('quantite_en_stock', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ActiviteCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_activite', models.DateField()),
                ('total_ventes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_transferts', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepot.centre')),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=15)),
                ('salaire_jour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepot.centre')),
            ],
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_achat', models.DateField()),
                ('montant_total_ht', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('montant_verse', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepot.fournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepot.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Reglement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_reglement', models.DateField()),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepot.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='ReglementClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_reglement', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_reglement', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepot.client')),
            ],
        ),
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('date_transfert', models.DateField()),
                ('cout_transfert', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('achat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entrepot.achat')),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepot.centre')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepot.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_vente', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('date_vente', models.DateField()),
                ('montant_encaisse', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('centre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entrepot.centre')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepot.client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepot.produit')),
            ],
        ),
    ]
