# Generated by Django 5.0 on 2024-01-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
