# Generated by Django 5.0 on 2024-01-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0002_client_isdeleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employe',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produit',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
