# Generated by Django 5.0 on 2024-01-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0003_centre_isdeleted_employe_isdeleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achat',
            name='montant_verse',
        ),
        migrations.AddField(
            model_name='achat',
            name='type_paiement',
            field=models.CharField(choices=[('total', 'Paiement total'), ('partiel', 'Paiement partiel')], default='total', max_length=15),
        ),
    ]
