# Generated by Django 5.0 on 2024-01-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0004_remove_achat_montant_verse_achat_type_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='montant_total_ht',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
