# Generated by Django 5.0 on 2024-01-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0005_alter_achat_montant_total_ht'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='centre',
        ),
        migrations.AddField(
            model_name='vente',
            name='credit_client',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
