# Generated by Django 5.0 on 2024-01-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0006_remove_vente_centre_vente_credit_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='type_paiement',
            field=models.CharField(choices=[('total', 'Paiement total'), ('partiel', 'Paiement partiel')], max_length=15),
        ),
    ]
