# Generated by Django 5.0 on 2024-01-07 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0007_alter_achat_type_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglement',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entrepot.produit'),
        ),
    ]
