# Generated by Django 5.0 on 2024-01-07 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0008_reglement_produit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fournisseur',
            name='isDeleted',
        ),
    ]
