# Generated by Django 5.0 on 2024-01-07 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0009_remove_fournisseur_isdeleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglement',
            name='achat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entrepot.achat'),
        ),
        migrations.AddField(
            model_name='reglement',
            name='prix_produit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
