# Generated by Django 5.0 on 2024-01-07 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0010_reglement_achat_reglement_prix_produit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reglement',
            name='prix_produit',
        ),
    ]
