# Generated by Django 5.0 on 2024-01-07 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0011_remove_reglement_prix_produit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reglement',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='reglement',
            name='produit',
        ),
        migrations.AddField(
            model_name='reglement',
            name='vente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entrepot.vente'),
        ),
    ]
