# Generated by Django 5.0 on 2024-01-09 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0012_remove_reglement_fournisseur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entrepot.centre'),
        ),
    ]
