# Generated by Django 5.0 on 2024-01-09 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0014_remove_vente_centre'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entrepot.centre'),
        ),
    ]
