# Generated by Django 5.0 on 2024-01-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0015_vente_centre'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='type_paiement',
            field=models.CharField(choices=[('total', 'Paiement total'), ('partiel', 'Paiement partiel')], default='Paiement total', max_length=15),
        ),
    ]
