# Generated by Django 5.0 on 2024-01-12 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0016_vente_type_paiement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='montant_encaisse',
        ),
    ]
