# Generated by Django 5.0 on 2024-01-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0017_remove_vente_montant_encaisse'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='montant_encaisse',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
