# Generated by Django 5.0 on 2024-01-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0019_absence_avance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='motif',
        ),
        migrations.RemoveField(
            model_name='avance',
            name='motif',
        ),
        migrations.AddField(
            model_name='absence',
            name='nombreAbscence',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
