# Generated by Django 5.0 on 2024-01-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0020_remove_absence_motif_remove_avance_motif_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='nombreAbscence',
        ),
        migrations.AddField(
            model_name='employe',
            name='nombreAbscence',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
