# Generated by Django 5.0 on 2024-01-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0021_remove_absence_nombreabscence_employe_nombreabscence'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='demandeAvance',
            field=models.BooleanField(default=False),
        ),
    ]
